export const enum ScreenName {
  SPLASH = 'SplashScreen',
  LOGIN = 'LoginScreen',
  FORGET_OTP = 'OtpScreen',
  MAINSCREEN = 'MainScreen',
  DASHBOARD = 'DashboardScreen',
  SYNCNOW = 'SyncNow',
  REFRESHDATA = 'RefreshData',
  SHOPS = 'Shops',
  DATACOLLECTION = 'DataCollection',
  DATACARDS = 'DataCards',
  ORDERS = 'Orders',
  ACTIVITY = 'Activity',
  COLLECTIONS = 'Collection',
  SURVEYS = 'Surveys',
  RESOURCES = 'ResourceLanding',
  DETAIL = 'DetailScreen',
  VideoPlayerScreen = 'VideoPlayerScreen',
  REPORTS = 'Reports',
  ADVANCEREPORTS = 'AdvanceReports',
  LOGOUT = 'LogOut',
  SOS = 'Sos',
  LIVELOCATIONMAPVIEW = 'LiveLocationMapView',

  // SHOP MODULE
  SHOPSFRONT = 'shopfront',
  SHOPSDETAIL = 'shopDetail',
  ORDER_VIEW_SHOP = 'OrderViewDetailsShops',
  ORDER_VIEW_EXTEND_SHOP = 'OrderViewExtended',
  //Add New Shops
  ADDNEWSHOPS1 = 'AddNewShop1',
  ADDNEWSHOPS2 = 'AddNewShop2',

  // COLLECTION MODULE
  OUTSTANDINGMAIN = 'PaymentsOutStandingLists',
  COLLECTIONMAIN = 'Collections',
  BOUNCEDCHEQUED = 'PaymentsBouncedChekedlist',
  COLLECTIONHISTORY = 'PaymentsHistoryList',
  ACCEPTPAYMENT = 'AcceptPayment',
  ACCEPTPAYMENT2 = 'AcceptPayment2',
  ALLPANDINGINVOICE = 'AllPandingInvoice',
  PREVIEWACCEPTPAYMENTSCREEN = 'PreviewAcceptPaymentScreen',
  COLLECTIONDETAILS = 'CollectionDetails',
  COLLECTIONHISTORYDETAILS = 'CollectionHistoryDetails',

  // CREATE NEW ORDER MODULE
  CREATENEWORDER1 = 'CreateNewOrderStep1',
  CREATENEWORDER2 = 'CreateNewOrderStep2',
  CREATENEWORDER3 = 'CreateNewOrderStep3',

  PARTIAL_DISCOUNT = 'PartialDiscountCNO',
  EDIT_PARTIAL_DISCOUNT = 'EditPartialDiscount',

  FULL_DISCOUNT = 'FullDiscountCNO',
  EDIT_FULL_DISCOUNT = 'EditFullDiscount',

  // SIDE ORDER MODULE
  SIDEORDERDETAIL = 'SideOrderDetail',
  EDIT_PARTIAL_SIDE_DISCOUNT = 'EditPartialDiscountSide',
  EDIT_FULL_SIDE_DISCOUNT = 'EditFullDiscountSide',

  // DATA COLLECTION MODULE
  DATACOLLECTIOSTEP1 = 'DataCollectionStep1',

  // QR/BarCode Scanner
  QR_BAR_SCANNER = 'QrBarScanner',

  //ActivtityModule
  CREATE_MEET = 'CreateMeet',
  CREATEMEETONE = 'CreateMeetOne',
  CANCELMEET = 'MJP_Cancel',
  ENDMEET = 'MJP_two',

  //AuditAsset
  ASSETUPDATE = 'AssestUpdate',
  AUDITEXIST = 'Audit Existing Asset',
  ADDNEW = 'Add New Asset',
  REPLACE = 'Replace Asset',
  DISCARD = 'Discard Asset',
  AUDITAASETSTEP2 = 'AuditAssetSteps2',
  AUDITAASETSTEP3 = 'AuditAssetStep3',
  ASSETDETAILS = 'AssetDetails',

  //AdvanceReports
  ADVACEREPORTMAIN = 'AdvanceReportsMain',
  PROCLAIMS = 'Proclaims',
  PROCLAIMZSCHEMEAPP = 'ProclaimzSchemeApp',
  PROCLAIMZSCHEMEDEF = 'ProclaimzSchemeDef',

  //Surveys
  AVAILABLESURVEYS = 'AvailableSurveys',
  DETAILVIEWSURVEYBROWSER = 'DetailViewSurveyBrowser',
  SURVEYTABNAV = 'SurveyTabNav',
  HISTORY = 'History',
  SURVEYWEBVIEW = 'CommonWebView',

  EXPANDLIST = 'ExpandList',

  // Reports
  OUTLET_PERFORMANCE1 = 'OutletPerformance1',
  OUTLET_PERFORMANCE2 = 'OutletPerformance2',
  VISIT_BASED = 'VisitBasedReport',
  OUTLETMYACTIVITYPARTYLIST = 'OutletMyActivityPatyList',
  MYACTIVTIYREPORT = 'MyActivityReport',
  OUTLETVISITREPORTS = 'OutletVisitReports',
  OUTLETVISITACTIVITY = 'OutletVisitActivity',
  BRAND_SALE_REPORT = 'BrandWiseSaleReport',
  TARGET_VS_ACHI_REP = 'TargetVsAchiReport',
  DISTRIBUTOR_DATA_STATUS = 'DistributorDataStatus',
  MAPVIEW_OUTLETS = 'NearByOutLets',
  MAPVIEW_OUTLETS_GEOFENCEVIEW = 'NearByOutLetsGeofence',
  LIVELOCATION_MAPVIEW = 'LiveLocationMapView',

  // POD
  POD = 'Proof of Delivery',
  POD_STEP2 = 'Proof of Delivery Step 2',
  POD_STEP3 = 'Proof of Delivery Step 3',

  // Dashboard
  DASHBOARD_NEGATIVE_SHOP = 'NegativeOutletsDashboard',
  DASHBOARD_T_VS_ACHI_WOD_REP = 'TargetVsAchievementandWODReport',
  DASHBOARD_BWS_REP = 'DashboardBWSReport',
  USER_OUTSTANDING_AGE_REP = 'UserOutstandingAgeReport',
  DASHBOARD_SALES_TREND_REP = 'DashboardSalesTrendReport',

  // Drawer info
  ABOUT_US = 'About_Us',
  PRIVACYPOLICY = 'PrivacyPolicy',
  SECURITY = 'Security',
}
export const enum AccessControlKeys {
  SHOPS = 1,
  DATACOLLECTION = 2,
  DATACARDS = 2,
  ORDERS = 4,
  ACTIVITY = 5,
  COLLECTIONS = 6,
  ADVANCEREPORTS = 7,
  SURVEYS = 8,
  RESOURCES = 9,
  REPORTS = 10,
  ASSETS = 11,
}

export const enum AccessControlKeyConstants {
  //SIDE MENU
  SIDE_MENU_SYNCNOW = 'SIDE_MENU_SYNCNOW',
  SIDE_MENU_REFRESHDATA = 'SIDE_MENU_REFRESHDATA',
  SIDE_MENU_SHOPS = 'SIDE_MENU_SHOPS',
  SIDE_MENU_DATACOLLECTION = 'SIDE_MENU_DATACOLLECTION',
  SIDE_MENU_DATACARDS = 'SIDE_MENU_DATACARDS',
  SIDE_MENU_ORDERS = 'SIDE_MENU_ORDERS',
  SIDE_MENU_ACTIVITY = 'SIDE_MENU_ACTIVITY',
  SIDE_MENU_COLLECTIONS = 'SIDE_MENU_COLLECTIONS',
  SIDE_MENU_SURVEYS = 'SIDE_MENU_SURVEYS',
  SIDE_MENU_REPORTS = 'SIDE_MENU_REPORTS',
  SIDE_MENU_ADVANCEREPORTS = 'SIDE_MENU_ADVANCEREPORTS',
  SIDE_MENU_LOGOUT = 'SIDE_MENU_LOGOUT',
  SIDE_MENU_REPORTERROR = 'SIDE_MENU_REPORTERROR',
  SIDE_MENU_RESOURCES = 'SIDE_MENU_RESOURCES',
  SIDE_MENU_POD = 'SIDE_MENU_POD',

  //FAB OPTIONS
  FAB_CREATE_ACTIVITY = 'FAB_CREATE_ACTIVITY',
  FAB_DATA_COLLECTION = 'FAB_DATA_COLLECTION',
  FAB_ADD_NEW_SHOP = 'FAB_ADD_NEW_SHOP',
  FAB_ACCEPT_COLLECTION = 'FAB_ACCEPT_COLLECTION',
  FAB_CREATE_NEW_ORDER = 'FAB_CREATE_NEW_ORDER',
  FAB_AUDIT_ASSET = 'FAB_AUDIT_ASSET',
  FAB_DASHBOARD = 'FAB_DASHBOARD',
  FAB_SHOP_DETAILS = 'FAB_SHOP_DETAILS',

  //DASHBOARD
  DASHBOARD = 'DASHBOARD',
  DASHBOARD_COLLECTION_STATUS = 'DASHBOARD_COLLECTION_STATUS',
  DASHBOARD_MARKET_CALLS = 'DASHBOARD_MARKET_CALLS',
  DASHBOARD_TVA = 'DASHBOARD_TVA',
  DASHBOARD_SALES_TREND = 'DASHBOARD_SALES_TREND',
  DASHBOARD_MARK_ATTENDANCE = 'DASHBOARD_MARK_ATTENDANCE',

  //DASHBOARD PERFORMANCE REPORT
  DASHBOARD_PERFORMANCE_REPORT = 'DASHBOARD_PERFORMANCE_REPORT',
  DASHBOARD_PERFORMANCE_TVA = 'DASHBOARD_PERFORMANCE_TVA', //TARGET VS ACHIVEMENT
  DASHBOARD_PERFORMANCE_WOD = 'DASHBOARD_PERFORMANCE_WOD', //WIDTH OF DISTRIBUTOR
  DASHBOARD_PERFORMANCE_BWS = 'DASHBOARD_PERFORMANCE_BWS', //BRAND WISE SALES
  DASHBOARD_PERFORMANCE_UBO = 'DASHBOARD_PERFORMANCE_UBO', //UNBILLED OUTLETS
  DASHBOARD_PERFORMANCE_UBP = 'DASHBOARD_PERFORMANCE_UBP', //UNBILLED PRODUCTS
  DASHBOARD_PERFORMANCE_NVO = 'DASHBOARD_PERFORMANCE_NVO', //NOT VISITED OUTLETS
  DASHBOARD_PERFORMANCE_OAR = 'DASHBOARD_PERFORMANCE_OAR', //OUTSTANDING AGEING REPORT
  DASHBOARD_PERFORMANCE_STR = 'DASHBOARD_PERFORMANCE_STR', //SALES TREND REPORT

  //REPORTS
  REPORT_BRAND_WISE_SALES = 'REPORT_BRAND_WISE_SALES',
  REPORT_TVA = 'REPORT_TVA', //TARGET VS ACHIVEMENT
  REPORT_DISTRIBUTOR_DATA_UPLOAD = 'REPORT_DISTRIBUTOR_DATA_UPLOAD',
  REPORT_OUTLET_VISIT_REPORTS = 'REPORT_OUTLET_VISIT_REPORTS',
  REPORT_OUTLET_MYACTIVITY_PARTYLIST = 'REPORT_OUTLET_MYACTIVITY_PARTYLIST',
  REPORT_OUTLET_PERFORMANCE_REPORT = 'REPORT_OUTLET_PERFORMANCE_REPORT',
  REPORT_VISIT_BASED_MAPVIEW = 'REPORT_VISIT_BASED_MAPVIEW',
  REPORT_LIVE_LOCATION_MAPVIEW = 'REPORT_LIVE_LOCATION_MAPVIEW',

  //SHOP DETAILS
  SHOP_DETAILS_CHECKIN_CHECKOUT = 'SHOP_DETAILS_CHECKIN_CHECKOUT',
  SHOP_DETAILS_PROFILE = 'SHOP_DETAILS_PROFILE',
  SHOP_DETAILS_TOTAL_OS = 'SHOP_DETAILS_TOTAL_OS',
  SHOP_DETAILS_VIEW_LEDGER = 'SHOP_DETAILS_VIEW_LEDGER',
  SHOP_DETAILS_LAST_3_MONTH_AVG = 'SHOP_DETAILS_LAST_3_MONTH_AVG',
  SHOP_DETAILS_LAST_SALES_ON = 'SHOP_DETAILS_LAST_SALES_ON',
  SHOP_DETAILS_LAST_ORDER_ON = 'SHOP_DETAILS_LAST_ORDER_ON',
  SHOP_DETAILS_ASSET_IMAGE = 'SHOP_DETAILS_ASSET_IMAGE',
  SHOP_DETAILS_IMAGE = 'SHOP_DETAILS_IMAGE',
  SHOP_DETAILS_MOST_FREQUENT_PURCHASE_BRAND = 'SHOP_DETAILS_MFPB', //MOST FREQUENT PURCHASE BRAND
  SHOP_DETAILS_PDC_DETAILS = 'SHOP_DETAILS_PDC_DETAILS',
  SHOP_DETAILS_UNALLOCATED_AMT = 'SHOP_DETAILS_UNALLOCATED_AMT',

  //ORDER PLACING
  ORDER_SCHEME_ON = 'ORDER_SCHEME_ON',
  ORDER_ADD_ITEM_DISC = 'ORDER_ADD_ITEM_DISC',
  ORDER_FILTER_ONE = 'ORDER_FILTER_ONE',
  ORDER_FILTER_TWO = 'ORDER_FILTER_TWO',
  ORDER_SEARCH_BRAND_MIC = 'ORDER_SEARCH_BRAND_MIC',
  ORDER_SEARCH_SHOP_MIC = 'ORDER_SEARCH_SHOP_MIC',
  ORDER_ADD_ORDER_DISC = 'ORDER_ADD_ORDER_DISC',
  ORDER_PREVIEW_SHARE = 'ORDER_PREVIEW_SHARE',

  //ORDER EDIT
  ORDER_EDIT_ADD_PRODUCT = 'ORDER_EDIT_ADD_PRODUCT',
  ORDER_EDIT_DELETE_ORDER = 'ORDER_EDIT_DELETE_ORDER',
  ORDER_EDIT_ORDER_EDIT = 'ORDER_EDIT_ORDER_EDIT',

  //COLLECTION
  COLLECTION_ADD_DISCOUNT = 'COLLECTION_ADD_DISCOUNT',

  //PAYMENT TYPES
  PAYMENT_TYPE_CASH = 'PAYMENT_TYPE_CASH',
  PAYMENT_TYPE_CHEQUE = 'PAYMENT_TYPE_CHEQUE',
  PAYMENT_TYPE_RTGS = 'PAYMENT_TYPE_RTGS',
  PAYMENT_TYPE_NEFT = 'PAYMENT_TYPE_NEFT',
}

export const enum DATE_FORMAT_CONSTANTS {
  GET_TIME_FORMAT_WITH_T = 'YYYY-MM-DDTHH:mm:ss',
  GET_DATE_DD_MMM_YYYY = 'DD-MMM-YYYY',
  GET_DATE_YYYY_MM_DD_HH_mm_ss = 'YYYY-MM-DD HH:mm:ss',
}

export const DEFAULT_TAB_NAMES = ['home', 'anotherTab']; // Add other tab IDs as needed

export const enum CODE_LIST {
  VERSION_MISMATCH_FORCE_UPDATE = '101',
}

export const enum FILE_NAMES {
  PREFIX_ORDER_PDF = 'order_pdf_',
  DOCUMENTS = 'Documents',
  PDF_EXTENTION = '.pdf',
}

export const enum ActionPerform {
  SYNC = 'sync',
  REFRESH_DATA = 'refresh_data',
  RERPORT_ERROR = 'report_error',
  RERPORT_ERROR_FULL_DB = 'report_full_db',
  LOGOUT = 'logout',
  RESET_DB_DATA = 'reset_db_data',
}

export const enum ApiConst {
  DATA_SAVED_SUCCESSFULLY = 'Data saved successfully.',
}

export const APP_VERSION_CHECK = 605;
export const VERSION_DETAIL = `App Version : 6.3.3`;
